### PR TITLE
Build image from base arg

### PR DESCRIPTION
**Pull request by sosheskaz**

### CODE REVIEW

**Review by nebulous — COMMENTED** [review]
This is acceptable as an arg but I’d love to know the reason for it vs changing the base image to something everyone can use ( I take it you’d be interested in a hass base) or just having your own docker file / sed. We might be able to mana things better for everyone with more context.

**Comment by sosheskaz** [comment]
The context is that I've put together a HA addon: https://github.com/sosheskaz/infinitude-ha-addon.

I am interested in changing the base to use hassio, as you suggest. I don't think that necessarily makes sense in other contexts though.

From a separation of concerns perspective, I would rather not use my own Dockerfile, as I'm not very knowledgeable about PHP, just integrating Infinitude as it exists with hassio — this allows me to isolate just the "glue", without needing to worry about code changes or dependencies, instead just being able to consume infinitude's source.

Another aspect is that I want immutable images for the sake of reliable upgrades and rollback — upgrading to a different image tag with each update has the nice characteristic in hassio of allowing me to make it appear in the UI as an upgrade, and to allow rollback by just reverting to an old image, and... in general, making any given commit in my addon a viable snapshot of state. In that vein, I would benefit from immutable versioning of infinitude itself.

The hassio layer also has some extra needs, mostly to translate from hassio vars into infinitude's config: https://github.com/sosheskaz/infinitude-ha-addon/blob/main/docker/run.sh. This isn't that big, but again, with separation of concerns, I'm not sure that makes sense to contribute upstream. I'd be open to that... I just recall reading in a previous convo somewhere that you did not have a viable setup for testing releases of a HA addon, whereas I'm able to run my own experimental branch for any changes that come up.

I'm open to any other way you'd like to split that up though; my submodule solution is hardly graceful.

Sidenote, I really appreciate the work you've done on this project! Very nice to actually be able to use my thermostat how I like.

**Comment by nebulous** [comment]
How about using a [mutli-stage build](https://docs.docker.com/build/building/multi-stage/)? I'm open to being convinced otherwise, and happy to help lower friction, but this just feels like the wrong place to solve this problem.

**Comment by sosheskaz** [comment]
ah, thought I'd responded to this. AFAIK there's no good way to go about using multi-arch builds for this. Because the base is the OS, we'd effectively want to either
* Copy over the OS into the infinitude image, which defeat the point of installing libraries from infinitude, and might be incompatible.
* Copy over infinitude and its deps into the other image, which have the same problem, because the versions of libraries in the infinitude image may not be the same in the other base.

I'm not familiar with any technique to get around this problem for these kinds of builds.

**Comment by nebulous** [comment]
I'm not quite following how this avoids or solves a multi-arch build problem, but it's also a small change which will make it easier for another contributor, so hey fine. merged.

**Pull request merged**
